# Generated by Django 6.0.8 on 2026-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="KES", max_length=8)),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("original", "Original allocation"),
                            ("supplementary", "Supplementary"),
                            ("revised", "Revised"),
                            ("recurrent", "Recurrent"),
                            ("development", "Development"),
                        ],
                        default="development",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-financial_year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("county_department", "County Department"),
                            ("county_government", "County Government"),
                            ("national_ministry", "National Ministry"),
                            ("agency", "Agency"),
                            ("oversight", "Oversight Body"),
                            ("other", "Other"),
                        ],
                        default="county_department",
                        max_length=40,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("water", "Water"),
                            ("health", "Health"),
                            ("education", "Education"),
                            ("roads", "Roads"),
                            ("energy", "Energy"),
                            ("sanitation", "Sanitation"),
                            ("agriculture", "Agriculture"),
                            ("markets", "Markets"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("county", models.CharField(db_index=True, max_length=120)),
                ("ward", models.CharField(blank=True, max_length=120)),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        help_text="Implementing contractor or firm as stated in source documents. Leave blank if unknown.",
                        max_length=255,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=8)),
                ("financial_year", models.CharField(blank=True, max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("approved", "Approved"),
                            ("procurement", "Procurement"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("delayed", "Delayed"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False,
                        help_text="Marks records created as labelled demo data.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("allocation", "Allocation"),
                            ("approval", "Approval"),
                            ("procurement", "Procurement"),
                            ("contract", "Contract"),
                            ("implementation", "Implementation"),
                            ("completion", "Completion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=8)),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
