# Generated by Django 6.0.8 on 2026-09-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetallocation",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="sources.sourcedocument",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.institution",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_documents",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="sources.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="budgetallocation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to="sources.evidence",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["county", "status"], name="projects_pr_county_5da8d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name"], name="projects_pr_name_11d782_idx"),
        ),
    ]
