# Generated by Django 6.0.8 on 2026-09-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
        ("sources", "0002_alter_sourcedocument_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["category"], name="projects_pr_categor_220446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["ward"], name="projects_pr_ward_9a431b_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["contractor"], name="projects_pr_contrac_2131c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["financial_year"], name="projects_pr_financi_9ce95a_idx"
            ),
        ),
    ]
