# Generated by Django 6.0.8 on 2026-09-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectview_projectfollow"),
        ("sources", "0003_sourcedocument_extracted_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="constituency",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["county", "constituency"], name="projects_pr_county_8ddd49_idx"
            ),
        ),
    ]
