# Generated by Django 6.0.8 on 2026-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_convert_legacy_integer_ids"),
        ("sources", "0004_alter_evidence_options_alter_evidence_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="country",
            field=models.CharField(db_index=True, default="KE", max_length=2),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["country", "county", "status"],
                name="projects_pr_country_7cc257_idx",
            ),
        ),
    ]
