# Generated by Django 6.0.8 on 2026-09-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(
                blank=True,
                help_text="Newsroom, university, department, or organisation — if you want it recorded.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="county",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, help_text="Town, ward, or area you follow.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("citizen", "Resident / citizen"),
                    ("journalist", "Journalist"),
                    ("researcher", "Researcher"),
                    ("student", "Student"),
                    ("official", "Public official"),
                    ("cso", "Civil society / oversight"),
                    ("other", "Other"),
                ],
                help_text="How you usually use this record. Optional.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Public name shown on your dashboard and avatar.",
                max_length=150,
            ),
        ),
    ]
