# Generated by Django 6.0.8 on 2026-09-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="area_last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="constituency",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="track_area",
            field=models.BooleanField(
                default=False,
                help_text="Show projects from this county on the dashboard.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ward",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
