# Generated by Django 6.0.8 on 2026-09-14 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_watches(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    AreaWatch = apps.get_model("accounts", "AreaWatch")
    for user in User.objects.filter(track_area=True).exclude(county=""):
        AreaWatch.objects.get_or_create(
            user=user,
            county=user.county,
            constituency=user.constituency or "",
            ward=user.ward or "",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_area_watch_and_project_constituency"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=120)),
                ("constituency", models.CharField(blank=True, max_length=120)),
                ("ward", models.CharField(blank=True, max_length=120)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_watches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["county", "constituency", "ward"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "county", "constituency", "ward"),
                        name="unique_user_area_watch",
                    )
                ],
            },
        ),
        migrations.RunPython(copy_existing_watches, migrations.RunPython.noop),
    ]
