# Generated by Django 6.0.8 on 2026-09-15 00:51

import uuid
from django.db import migrations, models

from apps.core.postgres_uuid import convert_tables


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_areawatch"),
    ]

    operations = [
        migrations.RunPython(convert_tables("accounts_user", "accounts_areawatch"), migrations.RunPython.noop),
        migrations.AlterField(
            model_name="areawatch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
