# Generated by Django 6.0.8 on 2026-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_areawatch_id_alter_user_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="areawatch",
            name="unique_user_area_watch",
        ),
        migrations.AddField(
            model_name="areawatch",
            name="country",
            field=models.CharField(db_index=True, default="KE", max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                db_index=True,
                default="KE",
                help_text="Country whose public record and administrative units you follow.",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="areawatch",
            constraint=models.UniqueConstraint(
                fields=("user", "country", "county", "constituency", "ward"),
                name="unique_user_country_area_watch",
            ),
        ),
    ]
