# Generated by Django 6.0.8 on 2026-09-14 21:42

import apps.core.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("publisher", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("procurement", "Procurement"),
                            ("contract", "Contract"),
                            ("policy", "Policy"),
                            ("audit", "Audit"),
                            ("government_report", "Government Report"),
                            ("tender", "Tender"),
                            ("project_report", "Project Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.SafeUploadTo("documents"),
                        validators=[apps.core.uploads.validate_upload],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "verification_level",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-publication_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim",
                    models.TextField(
                        help_text="The statement being supported or examined."
                    ),
                ),
                (
                    "evidence_text",
                    models.TextField(
                        blank=True,
                        help_text="What the source actually says. Leave blank if unavailable.",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partially_verified", "Partially Verified"),
                            ("conflicting", "Conflicting"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="projects.project",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_items",
                        to="sources.sourcedocument",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "evidence",
                "ordering": ["id"],
            },
        ),
    ]
