# Generated by Django 6.0.8 on 2026-09-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedocument",
            name="publisher",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
