# Generated by Django 6.0.8 on 2026-09-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_alter_sourcedocument_publisher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text extracted for search. Capped so large files stay usable.",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("empty", "No file"),
                    ("ready", "Searchable"),
                    ("failed", "Could not read file"),
                    ("skipped", "Type not extracted"),
                ],
                db_index=True,
                default="empty",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="original_filename",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["document_type", "publication_date"],
                name="sources_sou_documen_f5e880_idx",
            ),
        ),
    ]
