# Generated by Django 6.0.8 on 2026-09-15 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_sourcedocument_extracted_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidence",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name_plural": "evidence",
            },
        ),
        migrations.AlterField(
            model_name="evidence",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
