# Generated by Django 6.0.8 on 2026-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("description", models.TextField()),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("budget", "Budget Policy"),
                            ("procurement", "Procurement"),
                            ("access_to_information", "Access to Information"),
                            ("oversight", "Oversight"),
                            ("development", "Development"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "policies",
                "ordering": ["title"],
            },
        ),
    ]
