# Generated by Django 6.0.8 on 2026-09-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        ("projects", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="projects.institution",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="sources.sourcedocument",
            ),
        ),
    ]
