# Generated by Django 6.0.8 on 2026-09-15 00:51

import uuid
from django.db import migrations, models

from apps.core.postgres_uuid import convert_tables


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_alter_policy_title"),
    ]

    operations = [
        migrations.RunPython(convert_tables("policies_policy"), migrations.RunPython.noop),
        migrations.AlterField(
            model_name="policy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
