# Generated by Django 6.0.8 on 2026-09-15 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_alter_policy_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
