# Generated by Django 6.0.8 on 2026-09-14 21:42

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("observation", models.TextField(help_text="What did you observe?")),
                (
                    "location",
                    models.CharField(
                        help_text="Where did you observe it?", max_length=255
                    ),
                ),
                ("observed_at", models.DateField(help_text="When did you observe it?")),
                (
                    "official_information",
                    models.TextField(
                        help_text="What official information are you comparing against?"
                    ),
                ),
                (
                    "difference_description",
                    models.TextField(help_text="Describe the difference."),
                ),
                (
                    "evidence_description",
                    models.TextField(
                        blank=True,
                        help_text="Describe any supporting evidence you are submitting.",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.SafeUploadTo("investigations"),
                        validators=[apps.core.uploads.validate_upload],
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("disputed", "Disputed"),
                        ],
                        default="unverified",
                        max_length=30,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
