# Generated by Django 6.0.8 on 2026-09-15 00:00

import apps.core.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.core.uploads.SafeUploadTo("investigations"),
                        validators=[apps.core.uploads.validate_upload],
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="investigations.investigation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
